# Generated by Django 3.2.9 on 2022-01-18 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_imageprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imageprofile',
            old_name='uploadedDate',
            new_name='uploadedate',
        ),
    ]
